"use client";

import { createClient } from "@supabase/supabase-js";
import { useEffect, useState } from "react";

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
type A = { id: string; starts_at: string; status: "scheduled" | "confirmed" | "completed" | "cancelled"; service_ids: string[]; service_name_snapshot: string | null; professional_name_snapshot: string | null; barbershops: { name: string; slug: string }[] };
const fmt = (v: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(v));

export default function MeusAgendamentos() {
  const [items, setItems] = useState<A[]>([]), [message, setMessage] = useState("Carregando seus agendamentos..."), [busy, setBusy] = useState("");
  async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.replace("/entrar"); return; } const { data, error } = await supabase.from("appointments").select("id,starts_at,status,service_ids,service_name_snapshot,professional_name_snapshot,barbershops(name,slug)").eq("customer_id", user.id).order("starts_at", { ascending: false }); setItems((data || []) as A[]); setMessage(error ? "Não foi possível carregar seus agendamentos." : ""); }
  useEffect(() => { void load(); }, []);
  async function change(item: A, rebook = false) { if (!window.confirm(rebook ? "A reserva atual será cancelada e a agenda abrirá para você escolher outro horário. Continuar?" : "Cancelar este agendamento?")) return; setBusy(item.id); const { error } = await supabase.from("appointments").update({ status: "cancelled" }).eq("id", item.id); if (error) { setBusy(""); setMessage("Não foi possível atualizar este agendamento."); return; } const barbershop = item.barbershops[0]; if (rebook && barbershop) { window.location.assign(`/${barbershop.slug}?services=${item.service_ids.join(",")}`); return; } setMessage("Agendamento cancelado."); await load(); }
  return <main style={{ minHeight: "100vh", background: "#f6f2ed", fontFamily: "Arial,sans-serif", color: "#1b1714" }}><header style={{ background: "#171310", padding: "18px 7vw", display: "flex", justifyContent: "space-between" }}><a href="/" style={{ color: "white", fontWeight: 900, textDecoration: "none" }}>BARBEARIA<span style={{ color: "#e99358" }}>SP</span></a><a href="/" style={{ color: "#d7ccc0" }}>Encontrar barbearia</a></header><section style={{ maxWidth: 850, margin: "auto", padding: "42px 20px" }}><p style={{ color: "#d7612c", fontWeight: 800, fontSize: 12 }}>ÁREA DO CLIENTE</p><h1 style={{ font: "bold clamp(32px,5vw,52px) Georgia,serif", margin: "0 0 10px" }}>Meus agendamentos.</h1><p style={{ color: "#6d6257" }}>Reservas futuras podem ser canceladas ou reagendadas. As concluídas ficam no seu histórico.</p>{message && <p role="status" style={{ color: "#8c3430" }}>{message}</p>}<div style={{ display: "grid", gap: 12, marginTop: 24 }}>{items.map(item => <article key={item.id} style={{ background: "white", padding: 20, borderRadius: 10, border: "1px solid #e5ddd5", display: "flex", justifyContent: "space-between", gap: 15, flexWrap: "wrap" }}><div><b style={{ fontSize: 18 }}>{item.barbershops[0]?.name || "Barbearia"}</b><br /><span>{item.service_name_snapshot || "Serviço"} · {item.professional_name_snapshot || "Profissional"}</span><br /><small>{fmt(item.starts_at)}</small></div><div>{item.status === "cancelled" ? <b style={{ color: "#8c3430" }}>Cancelado</b> : item.status === "completed" ? <b style={{ color: "#286331" }}>Histórico concluído</b> : <div style={{ display: "flex", gap: 8 }}><button disabled={busy === item.id} onClick={() => void change(item, true)} style={{ padding: "10px 13px", border: 0, background: "#d7612c", color: "white", borderRadius: 6, fontWeight: 700 }}>Reagendar</button><button disabled={busy === item.id} onClick={() => void change(item)} style={{ padding: "10px 13px", border: "1px solid #b56a5f", background: "white", color: "#8c3430", borderRadius: 6, fontWeight: 700 }}>Cancelar</button></div>}</div></article>)}{!items.length && !message && <div style={{ background: "white", padding: 22, borderRadius: 9 }}>Você ainda não possui agendamentos.</div>}</div></section></main>;
}
