"use client";
import { useMemo, useState } from "react";

const customers = [
  { name: "Marcos Silva", phone: "(11) 99876-5432", email: "marcos@email.com", last: "Hoje, 09:00", visits: 8 },
  { name: "Lucas Almeida", phone: "(11) 98765-4321", email: "lucas@email.com", last: "Hoje, 10:00", visits: 4 },
  { name: "Pedro Santos", phone: "(11) 97654-3210", email: "pedro@email.com", last: "Hoje, 14:00", visits: 2 },
  { name: "André Costa", phone: "(11) 96543-2109", email: "andre@email.com", last: "Hoje, 16:00", visits: 12 },
];
const nav = <nav style={{ background: "#2a211c", padding: "12px 8vw", display: "flex", gap: 20, flexWrap: "wrap" }}><a href="/painel" style={{ color: "#d7ccc0", textDecoration: "none" }}>Dados cadastrais</a><a href="/painel/clientes" style={{ color: "#fff", fontWeight: 700, textDecoration: "none" }}>Clientes</a><a href="/painel/agenda" style={{ color: "#d7ccc0", textDecoration: "none" }}>Agenda</a><a href="/painel/relatorios" style={{ color: "#d7ccc0", textDecoration: "none" }}>Relatórios</a></nav>;
export default function Clientes() { const [search, setSearch] = useState(""); const rows = useMemo(() => customers.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) || item.phone.includes(search)), [search]); return <main style={{ minHeight: "100vh", background: "#f6f2ed", color: "#1b1714", fontFamily: "Arial, sans-serif" }}><header style={{ background: "#171310", color: "white", padding: "19px 8vw" }}><a href="/" style={{ color: "white", textDecoration: "none", fontWeight: 800 }}>BARBEARIA<span style={{ color: "#e99358" }}>SP</span></a></header>{nav}<div style={{ maxWidth: 1050, margin: "0 auto", padding: "42px 24px" }}><p style={{ color: "#d7612c", fontWeight: 800, fontSize: 12, letterSpacing: 1.5 }}>BASE DA BARBEARIA</p><h1 style={{ font: "bold clamp(34px,5vw,58px)/.95 Georgia,serif", margin: "0 0 12px" }}>Clientes.</h1><p style={{ color: "#6d6257" }}>Todos os clientes que já fizeram um agendamento ficam registrados aqui.</p><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nome ou celular" style={{ width: "100%", maxWidth: 450, boxSizing: "border-box", padding: 13, border: "1px solid #d9d0c8", borderRadius: 5, margin: "20px 0" }} /><section style={{ background: "white", borderRadius: 9, overflow: "hidden", border: "1px solid #e5ddd5" }}>{rows.map((item) => <article key={item.phone} style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr 1fr 100px", gap: 16, padding: 20, borderBottom: "1px solid #eee" }}><div><b>{item.name}</b><br /><small>{item.email}</small></div><div><b>Celular</b><br />{item.phone}</div><div><b>Último horário</b><br />{item.last}</div><div><b>{item.visits}</b><br /><small>visitas</small></div></article>)}</section></div></main>; }
